### ISSUE TITLE
setup the model function warning (setup_model_MegaLMM function)

### ISSUE THREAD

**Issue by Yansen0515** [deruncie/MegaLMM#9]
Hi,
I got a warning (please check below) when I run the "setup_model_MegaLMM function".
````
"Message d'avis :
as(<matrix>, "lgTMatrix") is deprecated since Matrix 1.5-0; do as(as(as(., "lMatrix"), "generalMatrix"), "TsparseMatrix") instead "
````

Do you think it will make problems for the following work? I met a problem in the "initialize_MegaLMM(MegaLMM_state) " function.
````
r in (function (cond):
   error evaluating argument 'x' when selecting a method for function 't': Need S4 class dgCMatrix for a mapped sparse matrix
````

If you know how to solve this problem, please let me know.

Kind regards,
Yansen

**Comment by deruncie** [comment]
I don’t think the warning was the issue, but I pushed a fix for that. Try re-installing the package and see if the warning and errors go away.

From: Yansen CHEN ***@***.***>
Date: Friday, March 10, 2023 at 12:54 AM
To: deruncie/MegaLMM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [deruncie/MegaLMM] setup the model function warning (setup_model_MegaLMM function) (Issue #9)

Hi,
I got a warning (please check below) when I run the "setup_model_MegaLMM function".

"Message d'avis :

as(<matrix>, "lgTMatrix") is deprecated since Matrix 1.5-0; do as(as(as(., "lMatrix"), "generalMatrix"), "TsparseMatrix") instead "

Do you think it will make problems for the following work? I met a problem in the "initialize_MegaLMM(MegaLMM_state) " function.

r in (function (cond):

   error evaluating argument 'x' when selecting a method for function 't': Need S4 class dgCMatrix for a mapped sparse matrix

If you know how to solve this problem, please let me know.

Kind regards,
Yansen

**Comment by Yansen0515** [comment]
Hello,

I update the MegaLMM package. 
Then, I still have the first warning, however, the second error from "initialize_MegaLMM" disappeared.
Thank you for your help.

Kind regards,
Yansen

**Comment by deruncie** [comment]
That is not what I was expecting! Can you re-post the warning you get? Is it exactly the same?

From: Yansen CHEN ***@***.***>
Date: Tuesday, March 14, 2023 at 8:41 AM
To: deruncie/MegaLMM ***@***.***>
Cc: Daniel E Runcie ***@***.***>, Comment ***@***.***>
Subject: Re: [deruncie/MegaLMM] setup the model function warning (setup_model_MegaLMM function) (Issue #9)

Hello,

I update the MegaLMM package.
Then, I still have the first warning, however, the second error from "initialize_MegaLMM" disappeared.
Thank you for your help.

Kind regards,
Yansen

**Comment by Yansen0515** [comment]
Hi，

Yes. It is exactly the same as before. 
And I use the same code and data as before (just update he package this time). 

````
Message d'avis :
as(<matrix>, "lgTMatrix") is deprecated since Matrix 1.5-0; do as(as(as(., "lMatrix"), "generalMatrix"), "TsparseMatrix") instead 
````


Kind regards,
Yansen
